'use strict';

module.exports = [
    'src',
    'src/images',
    'src/fonts',
    'src/styles',
    'src/scripts',
    'src/tests',
    'src/scripts/app',
    'src/scripts/app/behaviors',
    'src/scripts/app/collections',
    'src/scripts/app/models',
    'src/scripts/app/controllers',
    'src/scripts/app/routers',
    'src/scripts/app/apis',
    'src/scripts/app/views',
    'src/scripts/app/templates',
    'src/scripts/app/regions',
    'src/tests/specs',
    'src/tests/specs/collections',
    'src/tests/specs/models',
    'src/tests/specs/controllers',
    'src/tests/specs/routers',
    'src/tests/specs/apis',
    'src/tests/specs/views',
    'gulp',
    'gulp/tasks',
    'gulp/util'
];
